Repository itz-arnav/RACE-GAME-JS-BROWSER, pull requests merged in 2022-10, with the labels that each got.

#3 Did some changes
  style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, approved

#4 Clarified instructions to play the game
  index.html
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, approved

#5 Modified style.css
  style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, approved

#6 Created Index1 by ,also added table form in it.
  index1.html
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, approved

#9 Added Background Music when the game starts
  assets/audio/music.mp3
  index.html
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, approved, awesome

#8 modified index.html and css files
  index.html
  index1.html
  style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, approved

#10 Changes Some color in Road , and added a new song (no copyright song)
  assets/audio/newmusic.mp3
  index.html
  script.js
  style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, approved, awesome

#11 Update index.html
  index.html
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, approved

#12 Add files via upload css
  Login cs.html
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, approved

#13 changed Styling
  style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, approved, awesome

#14 Hacktoberfest added new car images and also added more styles
  assets/images/car2.jpg
  style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, approved, awesome

#15 Add files via upload
  assets/audio/Karan Aujla - Game Over(PagalWorld.com.se).mp3
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, approved, awesome

#16 Modified style.css
  style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, approved

#17 New player car added for better distinction from enemy cars
  assets/images/car3.png
  style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, approved, awesome

#18 Create styles.css
  styles.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#20 https://pixabay.com/vectors/car-vehicle-red-racing-game-145008/
  assets/images/car.png
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, approved, awesome

#19 Added my little change in background image and colour also
  RacingCar/Amandeep603
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, approved, awesome

#22 Added music for Game, its good you can use it to start the game. Please merge my request.
  tunetank.com_4160_gamer_by_decibel.mp3
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022, approved, awesome
